### ISSUE TITLE
ISC license

### ISSUE THREAD

**Issue by madtrick** [contentful-labs/keepachangelog#4]
Do we want to use the ISC license? From the `package.json` file (https://github.com/contentful-labs/keepachangelog/blob/master/package.json#L15): `"license": "ISC",`

**Comment by geigerzaehler** [comment]
Unless anyone (@grncdr ?) disagrees, I would like to keep it.
- Permissive
- OSI approved
- Basically equivalent to MIT but cleaner

**Comment by grncdr** [comment]
It's fine with me, it's also the default for `npm init` which lines up with our desire to use the "community default". @adityabhatt might also have an opinion here?

**Comment by adityab** [comment]
What @geigerzaehler said. :+1:

**Comment by madtrick** [comment]
Fine then : )
